#1: Add initial serial dependencies dockerfile
NimbleSM/DockerTestImages pull request #2
Opened 2023-08-03 15:54 UTC by pierrepebay

2023-08-08 21:31 UTC, stmcgovern approved these changes
This looks good as is. Some changes will be required in light of the CI changes pursued in NimbleSM PR346.

2023-08-08 22:51 UTC, nmm0 reviewed
Looking good -- do we need the extra github actions (the commit format and so on)?

2023-08-09 20:18 UTC, pierrepebay commented
> Looking good -- do we need the extra github actions (the commit format and so on)?

They're used on other projects so that's why I brought them here, but I'll let you decide if we keep them or not.

2023-08-10 15:44 UTC, nmm0 requested changes
Thanks for doing this -- overall I think we should change two things:

1. Let's get rid of the extra checks like the signed commit checking and so on since we don't need those
2. Can you build, but not push, the docker image on PRs? Right now it looks like the workflow only runs on main and always pushes. This way with PRs we can verify that the dependencies are working

2023-08-10 16:02 UTC, nmm0 requested changes
Woops one thing I missed, is the different environments have the same prefix for view. I think that might cause some issues with the different environments conflicting

2023-08-10 17:15 UTC, nmm0 requested changes
Scratch previous comment, lets just disable views since we are not using

```yaml
view: False
```

2023-08-16 17:49 UTC, nmm0 approved these changes
Great work, thank you!

2023-08-16 17:51 UTC, nmm0 commented
I will switch this over to my Sandia Dockerhub account before merging just FYI

2023-08-17 16:03 UTC, nmm0 commented on .github/workflows/build-and-push-docker-image.yml
> +          images: pierrpebay/nimblesm
```suggestion
          images: nmm0/nimblesm-base-env
```

2023-08-22 21:11 UTC, merged